### ISSUE TITLE
Svelte REPL warnings

### ISSUE THREAD

**Issue by cycle4passion** [kaashin/svelte-store-tools#1]
Multiple REPL warning on adding svelte-store-tools

![Screen Shot 2022-04-22 at 5 20 16 PM](https://user-images.githubusercontent.com/6192217/164795985-4f4b4d5c-5ca2-47cd-b099-8d708d75deb1.png)

ERROR: 'register is not defined' -> fix: import register separately.
ERROR: "process is not defined" error. This common to many 3rd party packages in Svelte REPL.
added some code to fix this.

However, clicking the svelte-store-tools does to expand

[Svelte REPL](https://svelte.dev/repl/2fea141f2dfe41acab0e5e3862478c48?version=3.47.0)

```js
<script>
	import { StoreTools, register } from 'svelte-store-tools';
	import { writable } from "svelte/store";
	
	// Code only for REPL
	window.process = {
		env: 'production'
	}
	
	let store = writable({
		id: "1",
		sections: [
			{
				id: "section1",
				required: true,
			},
			{
				id: "section2",
				required: false
			}
		]
	})
	
	register('store', store);
</script>

<pre>
{JSON.stringify($store,null,2)}
</pre>
<StoreTools />
```

**Comment by kaashin** [comment]
Thanks for pointing these out! These warnings should be cleaned out now.

**Comment by cycle4passion** [comment]
Hmm. New version giving another `error: Invalid package name "$app" (name can only contain URL-friendly characters)`
